### ISSUE TITLE
Matching [] throws in Sweet 0.7.2

### ISSUE THREAD

**Issue by apaleslimghost** [natefaubion/sparkler#18]
Simple test case:

``` js
function nope {
  [] => null
}
```

Throws the following error in Sweet.js 0.7.2:

```
/Users/matt/Projects/ParamTrie/node_modules/sweet.js/lib/sweet.js:117
                    throw err;
                          ^
TypeError: Cannot read property 'node' of undefined
    at groupRows$796 (eval at <anonymous> (/Users/matt/Projects/ParamTrie/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:941:67)
    at transformCase$795 (eval at <anonymous> (/Users/matt/Projects/ParamTrie/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:926:43)
    at transformCase$795 (eval at <anonymous> (/Users/matt/Projects/ParamTrie/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:930:45)
    at transformCase$795 (eval at <anonymous> (/Users/matt/Projects/ParamTrie/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:930:45)
    at transformCase$795 (eval at <anonymous> (/Users/matt/Projects/ParamTrie/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:930:45)
    at astToTree$793 (eval at <anonymous> (/Users/matt/Projects/ParamTrie/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:907:63)
    at compile$792 (eval at <anonymous> (/Users/matt/Projects/ParamTrie/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:897:55)
    at eval (eval at <anonymous> (/Users/matt/Projects/ParamTrie/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:1728:32)
    at eval (eval at <anonymous> (/Users/matt/Projects/ParamTrie/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:1729:22)
    at eval (eval at <anonymous> (/Users/matt/Projects/ParamTrie/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:1745:6)
```

**Comment by natefaubion** [comment]
Not sweet related. Just a glaring oversight on my part! The parse always emits a `Branch` node on `Len` for array-like things, when it should be emitting a `Leaf` if there are no children. The compiler is thus getting a `Branch` with no branches. I'll push a fix later today.

https://github.com/natefaubion/sparkler/blob/a8450ed378e41d41d26e3731fdb293cb56f7ac7d/src/parser.js#L300

**Comment by vendethiel** [comment]
:+1:
